services:
  cad-uwyo:
    build:
      context: .
      dockerfile: Dockerfile-CAD-UWYO
    volumes:
      - ./input_data/data.xml:/app/input_data/data.xml
    networks:
      - app-network

  citysim-solver:
    build:
      context: .
      dockerfile: Dockerfile-CitySim-Solver
    volumes:
      - ./input_data:/usr/src/app
      - ./output_data:/output_data
    depends_on:
      cad-uwyo:
        condition: service_completed_successfully
    networks:
      - app-network

  plot:
    build:
      context: .
      dockerfile: Dockerfile-Plot
    volumes:
      - ./output_data:/app/output_data
    depends_on:
      citysim-solver:
        condition: service_completed_successfully
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
